export const FETCH_GITHUB_DATA_SUCCESS = 'FETCH_GITHUB_DATA_SUCCESS';
export const FETCH_GITHUB_DATA_FAILED = 'FETCH_GITHUB_DATA_FAILED';
export const FETCH_GITHUB_DATA_LOADING = 'FETCH_GITHUB_DATA_LOADING';

export const SEND_INPUT_QUERY_PARAMS = 'SEND_INPUT_QUERY_PARAMS';
